# Generated by Django 3.0.5 on 2020-07-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='Untitled', max_length=60)),
                ('body', models.TextField(default='...', max_length=400)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(default=None)),
            ],
        ),
    ]
