# Generated by Django 3.0.5 on 2020-07-31 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_note_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='deadline',
        ),
    ]
