# Generated by Django 3.0.5 on 2020-08-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20200802_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
