# Generated by Django 3.0.5 on 2020-08-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_auto_20200802_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='deadline',
        ),
    ]
